### ISSUE TITLE
Name of node

### ISSUE THREAD

**Issue by cymplecy** [NanotechComputers/node-red-pushover#1]
Just a first glance, as an existing long time user user of node-red-contrib-pushover, you seem to have used a very strange name for your enhanced node

node-red-contrib-xxx is the preferred naming convention

node-red-contrib-pushover-glance would be the one to to come first to mind :)

**Comment by Kevin-Deason** [comment]
Hi Simon, thank you for taking the time to log an issue.

Node red has updated their naming convention guidelines on 31st January 2022 which applies to any new nodes published after that date and I am following the new naming convention.

You can see the documentation here: https://nodered.org/docs/creating-nodes/packaging#naming

I could not get the old node-red-contrib-pushover to work as the 'request' library used was deprecated and the repo is dead, hence the new node. This is mostly for my own benefit but I intend on extending the package to have more/all of pushover's features built in. it will be slow but in time it would get there.

**Comment by cymplecy** [comment]
Apologies!!!

I hadn't seen that piece of documentation
