### ISSUE TITLE
Send image

### ISSUE THREAD

**Issue by ulferi** [NanotechComputers/node-red-pushover#4]
**Describe the bug**
After update to latest version i cant send an image with pushover.
If i change the link to something that dosent exist it dosent send a push.
With the correct link it send a push but without the image!
The file is on the correct location an can be opened by file editor in Home Assistant.

**node-RED Version**
3.02

**Pushover App (please complete the following information):**
 - Android

**Package Version (please complete the following information):**
    @nanotechcomputers/node-red-pushover 1.1.0

**Comment by Kevin-Deason** [comment]
Hi @ulferi 

I will look into this and push a fix as soon as I can

**Comment by ulferi** [comment]
Thanks a lot!

**Comment by ulferi** [comment]
HI
Im sending the string in msg.image (/config/node-red/entre.jpg)
Im saving the image in a function and that works fine.

When i try this i get: "TypeError: Cannot read properties of undefined (reading 'name')"

Can you guide me!
Thanks
